/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appearance {
  'eyeColor' : string,
  'style' : string,
  'gender' : string,
  'hairColor' : string,
}
export interface PersistentGameState {
  'npcRelationships' : Array<[string, bigint]>,
  'questFlags' : Array<string>,
  'location' : string,
}
export interface PersonalityTraits {
  'agreeableness' : bigint,
  'extroversion' : bigint,
  'openness' : bigint,
}
export interface Protagonist {
  'background' : string,
  'appearance' : Appearance,
  'traits' : PersonalityTraits,
}
export interface Quest {
  'id' : string,
  'title' : string,
  'description' : string,
  'rewards' : Array<string>,
  'objectives' : Array<QuestObjective>,
}
export interface QuestJournalEntry {
  'state' : { 'completed' : null } |
    { 'inProgress' : null } |
    { 'failed' : null },
  'questId' : string,
  'objectives' : Array<QuestObjective>,
}
export interface QuestObjective {
  'description' : string,
  'isComplete' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'createdAt' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestToPlayer' : ActorMethod<[string], undefined>,
  'advanceDialogue' : ActorMethod<[string, bigint], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeQuest' : ActorMethod<[string], undefined>,
  'createProtagonist' : ActorMethod<
    [Appearance, PersonalityTraits, string],
    undefined
  >,
  'createQuest' : ActorMethod<[Quest], undefined>,
  'getActiveQuests' : ActorMethod<[], Array<QuestJournalEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPersistentGameState' : ActorMethod<[], [] | [PersistentGameState]>,
  'getProtagonist' : ActorMethod<[], [] | [Protagonist]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateQuestProgress' : ActorMethod<[string, bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];