/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appearance = IDL.Record({
  'eyeColor' : IDL.Text,
  'style' : IDL.Text,
  'gender' : IDL.Text,
  'hairColor' : IDL.Text,
});
export const PersonalityTraits = IDL.Record({
  'agreeableness' : IDL.Nat,
  'extroversion' : IDL.Nat,
  'openness' : IDL.Nat,
});
export const QuestObjective = IDL.Record({
  'description' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const Quest = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'rewards' : IDL.Vec(IDL.Text),
  'objectives' : IDL.Vec(QuestObjective),
});
export const QuestJournalEntry = IDL.Record({
  'state' : IDL.Variant({
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'questId' : IDL.Text,
  'objectives' : IDL.Vec(QuestObjective),
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const PersistentGameState = IDL.Record({
  'npcRelationships' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'questFlags' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Protagonist = IDL.Record({
  'background' : IDL.Text,
  'appearance' : Appearance,
  'traits' : PersonalityTraits,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestToPlayer' : IDL.Func([IDL.Text], [], []),
  'advanceDialogue' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeQuest' : IDL.Func([IDL.Text], [], []),
  'createProtagonist' : IDL.Func(
      [Appearance, PersonalityTraits, IDL.Text],
      [],
      [],
    ),
  'createQuest' : IDL.Func([Quest], [], []),
  'getActiveQuests' : IDL.Func([], [IDL.Vec(QuestJournalEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersistentGameState' : IDL.Func(
      [],
      [IDL.Opt(PersistentGameState)],
      ['query'],
    ),
  'getProtagonist' : IDL.Func([], [IDL.Opt(Protagonist)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateQuestProgress' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appearance = IDL.Record({
    'eyeColor' : IDL.Text,
    'style' : IDL.Text,
    'gender' : IDL.Text,
    'hairColor' : IDL.Text,
  });
  const PersonalityTraits = IDL.Record({
    'agreeableness' : IDL.Nat,
    'extroversion' : IDL.Nat,
    'openness' : IDL.Nat,
  });
  const QuestObjective = IDL.Record({
    'description' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const Quest = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'rewards' : IDL.Vec(IDL.Text),
    'objectives' : IDL.Vec(QuestObjective),
  });
  const QuestJournalEntry = IDL.Record({
    'state' : IDL.Variant({
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'questId' : IDL.Text,
    'objectives' : IDL.Vec(QuestObjective),
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'createdAt' : Time });
  const PersistentGameState = IDL.Record({
    'npcRelationships' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'questFlags' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Protagonist = IDL.Record({
    'background' : IDL.Text,
    'appearance' : Appearance,
    'traits' : PersonalityTraits,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestToPlayer' : IDL.Func([IDL.Text], [], []),
    'advanceDialogue' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeQuest' : IDL.Func([IDL.Text], [], []),
    'createProtagonist' : IDL.Func(
        [Appearance, PersonalityTraits, IDL.Text],
        [],
        [],
      ),
    'createQuest' : IDL.Func([Quest], [], []),
    'getActiveQuests' : IDL.Func([], [IDL.Vec(QuestJournalEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersistentGameState' : IDL.Func(
        [],
        [IDL.Opt(PersistentGameState)],
        ['query'],
      ),
    'getProtagonist' : IDL.Func([], [IDL.Opt(Protagonist)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateQuestProgress' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };